import Hero from "@/components/home/Hero";
import Link from "next/link";
import { ArrowRight, Bot, Code2, FolderKanban, Laptop, GraduationCap } from "lucide-react";

export default function Home() {
  return (
    <div className="w-full">
      <Hero />
      
      {/* Popular Categories */}
      <section className="py-20 relative">
        <div className="container mx-auto px-4 md:px-8">
          <div className="flex flex-col md:flex-row md:items-end justify-between mb-12 gap-4">
            <div>
              <h2 className="text-3xl md:text-4xl font-bold font-heading mb-4">
                Explore <span className="text-[var(--neon-blue)] text-glow-blue">Categories</span>
              </h2>
              <p className="text-gray-400 max-w-2xl">Find everything you need from web development to artificial intelligence, tailored for beginners and pros alike.</p>
            </div>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <CategoryCard title="Web Development" icon={<Laptop className="w-8 h-8 text-[var(--neon-blue)]" />} count="24 Articles" link="/blog" />
            <CategoryCard title="AI & Machine Learning" icon={<Bot className="w-8 h-8 text-[var(--neon-green)]" />} count="18 Tools" link="/ai-tools" />
            <CategoryCard title="Data Structures" icon={<Code2 className="w-8 h-8 text-purple-400" />} count="32 Tutorials" link="/blog" />
            <CategoryCard title="Student Productivity" icon={<GraduationCap className="w-8 h-8 text-pink-400" />} count="15 Resources" link="/resources" />
          </div>
        </div>
      </section>

      {/* Trending AI Tools */}
      <section className="py-20 relative bg-[rgba(255,255,255,0.02)] border-y border-[var(--glass-border)]">
        <div className="absolute left-0 top-1/2 -translate-y-1/2 w-64 h-64 bg-[var(--neon-blue)] blur-[150px] opacity-10 rounded-full"></div>
        <div className="container mx-auto px-4 md:px-8 relative z-10">
          <div className="flex flex-col md:flex-row md:items-end justify-between mb-12 gap-4">
            <div>
              <h2 className="text-3xl md:text-4xl font-bold font-heading mb-4">
                Trending <span className="text-[var(--neon-green)] text-glow-green">AI Tools</span>
              </h2>
              <p className="text-gray-400 max-w-2xl">Supercharge your workflow with the most powerful AI applications available today.</p>
            </div>
            <Link href="/ai-tools" className="flex items-center gap-2 text-[var(--neon-blue)] hover:text-white transition-colors group">
              View all tools <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </Link>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <ToolCard 
              name="CodeCompanion AI" 
              desc="Your intelligent pair programmer that understands your codebase context deeply." 
              tags={["Coding", "Productivity"]} 
            />
            <ToolCard 
              name="WriteGenius" 
              desc="Generate high-quality blog posts, documentation, and emails in seconds." 
              tags={["Writing", "Content"]} 
            />
            <ToolCard 
              name="LearnFlow" 
              desc="Personalized learning paths generated by AI based on your goals." 
              tags={["Education", "Students"]} 
            />
          </div>
        </div>
      </section>

      {/* Coding Resources */}
      <section className="py-20 relative">
        <div className="absolute right-0 top-1/2 -translate-y-1/2 w-64 h-64 bg-[var(--neon-green)] blur-[150px] opacity-10 rounded-full"></div>
        <div className="container mx-auto px-4 md:px-8 relative z-10">
          <div className="flex flex-col md:flex-row md:items-end justify-between mb-12 gap-4">
            <div>
              <h2 className="text-3xl md:text-4xl font-bold font-heading mb-4">
                Latest <span className="text-white">Articles</span>
              </h2>
              <p className="text-gray-400 max-w-2xl">Read our latest thoughts on programming, architecture, and tech trends.</p>
            </div>
            <Link href="/blog" className="flex items-center gap-2 text-[var(--neon-blue)] hover:text-white transition-colors group">
              Read blog <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </Link>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <BlogCard 
              title="Mastering React Three Fiber for Futuristic UIs"
              excerpt="Learn how to integrate 3D elements into your React applications to create mind-blowing web experiences."
              date="May 15, 2026"
              readTime="8 min read"
            />
            <BlogCard 
              title="The Ultimate Guide to Next.js 15 App Router"
              excerpt="Discover the new features in Next.js 15 and how to optimize your application for maximum performance."
              date="May 10, 2026"
              readTime="12 min read"
            />
          </div>
        </div>
      </section>
    </div>
  );
}

function CategoryCard({ title, icon, count, link }: { title: string, icon: React.ReactNode, count: string, link: string }) {
  return (
    <Link href={link} className="glass-panel p-6 rounded-2xl flex flex-col items-center text-center glass-hover group cursor-pointer">
      <div className="w-16 h-16 rounded-full bg-[rgba(255,255,255,0.05)] flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-300">
        {icon}
      </div>
      <h3 className="text-lg font-bold mb-2 group-hover:text-[var(--neon-blue)] transition-colors">{title}</h3>
      <p className="text-sm text-gray-400">{count}</p>
    </Link>
  );
}

function ToolCard({ name, desc, tags }: { name: string, desc: string, tags: string[] }) {
  return (
    <div className="glass-panel p-6 rounded-2xl glass-hover flex flex-col h-full">
      <div className="w-12 h-12 rounded-xl bg-[rgba(57,255,20,0.1)] flex items-center justify-center mb-6 border border-[rgba(57,255,20,0.2)]">
        <Bot className="w-6 h-6 text-[var(--neon-green)]" />
      </div>
      <h3 className="text-xl font-bold mb-3">{name}</h3>
      <p className="text-gray-400 mb-6 flex-grow">{desc}</p>
      <div className="flex flex-wrap gap-2 mb-6">
        {tags.map(tag => (
          <span key={tag} className="px-3 py-1 text-xs font-medium rounded-full bg-[rgba(255,255,255,0.05)] border border-[var(--glass-border)] text-gray-300">
            {tag}
          </span>
        ))}
      </div>
      <button className="w-full py-3 rounded-lg border border-[var(--neon-blue)] text-[var(--neon-blue)] font-medium hover:bg-[var(--neon-blue)] hover:text-black transition-all">
        Visit Tool
      </button>
    </div>
  );
}

function BlogCard({ title, excerpt, date, readTime }: { title: string, excerpt: string, date: string, readTime: string }) {
  return (
    <Link href="/blog" className="group glass-panel rounded-2xl overflow-hidden glass-hover flex flex-col md:flex-row h-full">
      <div className="md:w-2/5 h-48 md:h-auto bg-gray-800 relative overflow-hidden">
        {/* Placeholder for image */}
        <div className="absolute inset-0 bg-gradient-to-br from-blue-900/40 to-green-900/40 group-hover:scale-105 transition-transform duration-500"></div>
        <div className="absolute inset-0 flex items-center justify-center opacity-50">
          <FolderKanban className="w-12 h-12 text-gray-500" />
        </div>
      </div>
      <div className="p-6 md:w-3/5 flex flex-col justify-center">
        <div className="flex items-center gap-4 text-xs text-gray-400 mb-3">
          <span>{date}</span>
          <span className="w-1 h-1 rounded-full bg-gray-600"></span>
          <span>{readTime}</span>
        </div>
        <h3 className="text-xl font-bold mb-3 group-hover:text-[var(--neon-blue)] transition-colors line-clamp-2">{title}</h3>
        <p className="text-gray-400 text-sm line-clamp-3">{excerpt}</p>
      </div>
    </Link>
  );
}
